version: 0.2

env:
  variables:
    # This S3 bucket will be used to store the packaged Lambda deployment bundle.
    # Make sure to provide a valid S3 bucket name (it must exist already).
    # The AWS CodeBuild IAM role must allow write access to it.
    S3_BUCKET: "emopti-devops-provision"
    PACKAGE: "test"

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

      # Both /go and CODEBUILD_SRC_DIR are on CodeBuild's GOPATH, dep doesn't like symlinks between competing GOPATHs
      - export GOPATH="/go"

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

      # Install golint
      - go get -u github.com/golang/lint/golint

  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"

      # Fetch all dependencies
      - dep ensure -v

      # Assemble a list of things to build
      - export GO_BUILD_LIST=`go list ./...`

      # Ensure code passes all lint tests
      - golint -set_exit_status $GO_BUILD_LIST

      # Check the Go code for common problems with 'go vet'
      - go vet -v $GO_BUILD_LIST

      # Run all tests included with our application
      - go test -v $GO_BUILD_LIST

  build:
    commands:
    
      # Build our go application
      - go build -v -o main $GO_BUILD_LIST

      # Package our application with AWS SAM
      #- aws cloudformation package --template-file cfn-template.yaml --s3-bucket ${S3_BUCKET} --s3-prefix cfn/${PACKAGE}/packaged --output-template-file cfn-template-packaged.yaml

      #- echo Generating build-info.json ...
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "CODEBUILD_SOURCE_VERSION: $CODEBUILD_SOURCE_VERSION"


      #- echo -e "{\"codeBuildId\":\""$CODEBUILD_BUILD_ID"\",\"buildNumber\":\""$BUILD_NUMBER"\", \"buildTimestamp\":\""$(date -u +'%Y-%m-%dT%H:%M:%SZ')"\", \"sourceType\":\"GIT\", \"sourceVersion\":\""$GIT_COMMIT"\", \"sourceRepoUrl\":\""$GIT_URL"\", \"gitBranch\":\""$GIT_BRANCH"\" }" > ${CODEBUILD_SRC_DIR}/build-info.json

artifacts:
  files:
    - build-info.json
    - cfn-template.yaml
    - cfn-template-packaged.yaml
  discard-paths: yes
